# Generated by Django 2.2.12 on 2020-06-07 18:39

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups_list', djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='groups.Group')),
            ],
        ),
    ]
