# Generated by Django 2.2.12 on 2020-06-07 18:39

from django.db import migrations, models
import djongo.models.fields
import inattendances.models
import marks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inattendances_list', djongo.models.fields.ArrayField(default=[], model_container=inattendances.models.Inattendance)),
                ('marks_list', djongo.models.fields.ArrayField(default=[], model_container=marks.models.Mark)),
                ('final_grade', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
