# Generated by Django 2.2.12 on 2020-06-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0.0)),
                ('max_points', models.IntegerField(default=0.0)),
                ('for_what', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
