# Generated by Django 2.2.11 on 2020-04-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=120),
        ),
    ]
