# Generated by Django 2.2.12 on 2020-04-05 13:44

from django.db import migrations, models
from djongo.models.fields import ArrayField
import groups.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=120)),
                ('date_time', ArrayField(blank=True, model_container=groups.models.DayTime, null=True)),
                ('lecturers_list', ArrayField(blank=True, model_container=groups.models.Lecture, null=True)),
                ('enrolled_list', ArrayField(blank=True, model_container=groups.models.Enrolled, null=True)),
            ],
        ),
    ]
