# Generated by Django 2.2.12 on 2020-06-07 18:39

import dayTime.models
from django.db import migrations, models
import djongo.models.fields
import enrolleds.models
import lectures.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=120)),
                ('date_time', djongo.models.fields.ArrayField(blank=True, model_container=dayTime.models.DayTime, null=True)),
                ('lectures_list', djongo.models.fields.ArrayField(blank=True, model_container=lectures.models.Lecture, null=True)),
                ('enrolled_list', djongo.models.fields.ArrayField(blank=True, model_container=enrolleds.models.Enrolled, null=True)),
                ('course_end', models.BooleanField(default=False)),
            ],
        ),
    ]
