# Generated by Django 2.2.12 on 2020-05-11 12:46

from django.db import migrations, models
import djongo.models.fields
import groups.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inattendances_list', djongo.models.fields.ArrayField(default=[], model_container=groups.models.Inattendence)),
                ('marks_list', djongo.models.fields.ArrayField(default=[], model_container=groups.models.Mark)),
                ('final_grade', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=120)),
                ('date_time', djongo.models.fields.ArrayField(blank=True, model_container=groups.models.DayTime, null=True)),
                ('lectures_list', djongo.models.fields.ArrayField(blank=True, model_container=groups.models.Lecture, null=True)),
                ('enrolled_list', djongo.models.fields.ArrayField(blank=True, model_container=groups.models.Enrolled, null=True)),
                ('course_end', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inattendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.IntegerField()),
                ('justified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_lecture', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0.0)),
                ('max_points', models.IntegerField(default=0.0)),
                ('for_what', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
