# Generated by Django 2.2.12 on 2020-04-05 16:35

from django.db import migrations, models
import djongo.models.fields
import groups.models


class Migration(migrations.Migration):
    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('inattendances_list',
                 djongo.models.fields.ArrayField(blank=True, model_container=groups.models.Inattendence, null=True)),
                ('marks_list',
                 djongo.models.fields.ArrayField(blank=True, model_container=groups.models.Mark, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inattendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.IntegerField()),
                ('justified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_id', models.IntegerField()),
                ('main_lecture', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('for_what', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
