# Generated by Django 2.2.12 on 2020-05-25 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_auto_20200511_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups_list', djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='groups.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
